#!/usr/bin/env bash
# Generates INDEX.md — flat list of all problems, grouped by topic.
set -euo pipefail
out=INDEX.md

# Make sure we are in the script's directory
cd "$(dirname "$0")"

if [ ! -d topics ]; then
  echo "No 'topics' directory found."
  exit 1
fi

total=$(find topics -name '*.md' ! -name 'README.md' | wc -l | tr -d ' ')
{
  echo "# INDEX — All Problems"
  echo
  echo "Flat, generated index of every mathematical problem and conjecture (grouped by topic). **Total: ${total} problems.**"
  echo "Generated by \`gen_index.sh\`. See [TAXONOMY.md](./TAXONOMY.md) for topic descriptions."
  echo
  
  # Sort directory names numerically or alphabetically
  for d in $(find topics -maxdepth 1 -mindepth 1 -type d | sort); do
    slug=$(basename "$d")
    
    # Skip if it is not a topic directory (doesn't start with digits)
    if [[ ! "$slug" =~ ^[0-9] ]]; then
      continue
    fi
    
    # topic display name from the topic README H1
    name=""
    if [ -f "$d/README.md" ]; then
      name=$(grep -m1 '^# ' "$d/README.md" | sed 's/^# //')
    fi
    [ -z "$name" ] && name="$slug"
    
    cnt=$(find "$d" -name '*.md' ! -name 'README.md' | wc -l | tr -d ' ')
    echo "## ${name} (${cnt})"
    echo
    echo "Dir: [\`${slug}\`](./topics/${slug}/)"
    echo
    
    # Find and sort all markdown files except README.md
    # Using python or sort to avoid find output order issues
    find "$d" -name '*.md' ! -name 'README.md' | sort | while read -r f; do
      fn=$(basename "$f")
      title=$(grep -m1 '^# ' "$f" | sed 's/^# //')
      [ -z "$title" ] && title="$fn"
      echo "- [${title}](./topics/${slug}/${fn})"
    done
    echo
  done
} > "$out"
echo "Wrote $out with $total problems."
